name: Develop CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Validate HTML
        run: npx htmlhint "**/*.html" || true

      - name: Validate CSS
        run: npx stylelint "assets/css/**/*.css" || true
